### ISSUE TITLE
version 1.00 doesn't seem to solve the suspend issue

### ISSUE THREAD

**Issue by Slhdono** [dots-tb/rePatch-reDux0#1] opened 2018-03-30 16:30 UTC
First of all thank you for all your hard work
Here is the issue: The v0.4 works just fine but when I replace the v1.00 and reboot my 3.65 enso vita;
games will stuck on the opening screen and no errors it just stuck on the game's photo, I waited 5 mins there; I tried it on P4D undub and Senren Kagura EV both installed with nonpdrm.

Also it's better to mention I'm using sd2vita.

**Comment by dots-tb** [comment] 2018-03-31 06:01
The Persona 4 undub is confirmed to work on reDux0, it has been tested many times. (Persona 4 Golden improved UNDUB(v1.03) [US][NoNpDRM][PCSE00120] .zip by Radziu). For Senren Kagura, I'm not sure since some guy was testing it but it had a modified eboot (not sure which Senren Kagura though).

Please make sure that your games are updated through Live Area and that you have not deleted files that are necessary. As for it working with 0.4, it is less capable of capturing IO calls.

**Comment by IcySon55** [comment] 2018-03-31 06:05
Your P4D undub is bad. Please follow this tutorial to get it working properly with 1.0:
https://www.reddit.com/r/VitaPiracy/comments/86zkuz/repatch_redux0_10_fixed_suspend_issue_use_mods_on/dwafocm/

**Comment by Slhdono** [comment] 2018-03-31 10:17
"As for it working with 0.4, it is less capable of capturing IO calls." I couldn't  get your point here, I tried it on some other games too like FF X-2 Undub, all these games are using rePatch files to run and the main folder in app folder is not the full game (the original files are deleted and the game's loading up depends on rePatch folder) they will run on v0.4 no problem but with v1.00 they don't. the moment I replace v0.4 and reboot they run again no problem. but there is suspend issue which I need to upgrade to v1.00 , I hope there will be a solution for this.

**Comment by dots-tb** [comment] 2018-03-31 19:35
It has been tested many times on P4DAN, the suspend issue is fixed and it runs perfectly. 

Also, please download your games from NPS.

**Comment by Slhdono** [comment] 2018-03-31 21:59
I always download from NPS except when I need undub patch.
Thank you for your response, I will see what I can do.

**Comment by dots-tb** [comment] 2018-04-01 02:26
Alright, let me know the results. I hope it works out for you, good luck! :) @Slhdono

**Comment by dots-tb** [comment] 2018-04-19 22:31
I will close this for now since there is no further responses ?

**Closed by dots-tb** 2018-04-19 22:31 UTC
Labels: invalid, question
